# Generated by Django 4.2.3 on 2023-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaprequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default='Default image'),
            preserve_default=False,
        ),
    ]
